export const actionType = {
  INCREACE: 'INCREASE',
  DECREASE: 'DECREASE',
  ADD_PRODUCT: 'ADD_PRODUCT',
  REMOVE_PRODUCT: 'REMOVE_PRODUCT',
  CLEAR_CART: 'CLEAR_CART',
  HANDLE_CHECKOUT: 'HANDLE_CHECKOUT' 
}